version: "3"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
    volumes:
      - ./:/code
    ports:
      - "5005:80"


  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=allocation
      - POSTGRES_PASSWORD=abc123
      - PGDATA=/data
    ports:
      - "54321:5432"
    volumes:
      - "pg-database:/data"


volumes:
  pg-database:

